languageCode = "en-us"
title = "Linkfire Frontend Guidelines"
baseURL = "https://getlinkfire.github.io/frontend/"
canonifyURLs = true
theme = "cupper"
publishDir = "docs"

[params]
  description = "Frontend Guidelines documentation used at Linkfire"
